### ISSUE TITLE
How is the secure environment variable being encrypted?

### ISSUE THREAD

**Issue by geshan** [shippableSamples/sample-hipchat-notifications#2]
Are you using [travis encrypt](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables) for securing the variables seen on [line 10](https://github.com/shippableSamples/sample-hipchat-notifications/blob/master/shippable.yml#L10) of the shippable.yml file? How is it being encrypted?

**Comment by rolandpoulter** [comment]
No, on Shippable you must use the Encrypt Environment Variables dialog:
1. Login to Shippable.com.
2. Go to the subscription page which contains the project you want to add secure variables too.
3. Click the button that looks like this in the top right area of the page:

![image](https://cloud.githubusercontent.com/assets/51327/6008978/8899e9ec-aada-11e4-9567-524f45cc2f0b.png)

**Comment by geshan** [comment]
thanks.
